name: Validações antes do PR

on: 
  pull_request:
    branches:
      - master 

jobs: 
  linux_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
    - uses: actions/setup-node@v4

    with:
      node-version: '20.x'
    
    steps:
    - name: Instala deps.
      run: npm install
    - name: Executa build
      run: npx tsc
    - name: Executaando testes
      run: npm test